### ISSUE TITLE
[BUG] rel info fails on mmx4.rel from Mega Man X Collection

### ISSUE THREAD

**Issue by sozud** [encounter/decomp-toolkit#76]
### Game Name

Mega Man X Collection

### Game Version

MEGAMAN X COLLECTION (Disc 1, Revision 0)

### Description

The commands fails like:
```
thread 'main' panicked at src/analysis/cfa.rs:66:48:
attempt to add with overflow
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:74:14
   2: core::panicking::panic_const::panic_const_add_overflow
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:181:21
   3: <dtk::analysis::cfa::SectionAddress as core::ops::arith::Add<u32>>::add
             at ./src/analysis/cfa.rs:66:48
   4: dtk::analysis::vm::VM::step
             at ./src/analysis/vm.rs:211:70
   5: dtk::analysis::executor::Executor::run
             at ./src/analysis/executor.rs:114:30
   6: dtk::analysis::slices::FunctionSlices::analyze
             at ./src/analysis/slices.rs:442:22
   7: dtk::analysis::cfa::AnalyzerState::process_function
             at ./src/analysis/cfa.rs:454:18
   8: dtk::analysis::cfa::AnalyzerState::process_function_at
             at ./src/analysis/cfa.rs:415:38
   9: dtk::analysis::cfa::AnalyzerState::process_functions
             at ./src/analysis/cfa.rs:402:21
  10: dtk::analysis::cfa::AnalyzerState::detect_functions
             at ./src/analysis/cfa.rs:279:9
  11: dtk::cmd::rel::info
             at ./src/cmd/rel.rs:414:5
  12: dtk::cmd::rel::run
             at ./src/cmd/rel.rs:117:37
  13: dtk::main::{{closure}}
             at ./src/main.rs:177:36
  14: core::result::Result<T,E>::and_then
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/result.rs:1346:22
  15: dtk::main
             at ./src/main.rs:165:14
  16: core::ops::function::FnOnce::call_once
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5
```

The values of  address and rhs are 
```
0x1d4a00 0xfffffc00
```
So it seems like `rhs` can be negative.

Doing `self.address.wrapping_add(rhs)` seems to fix it:

```
RUST_BACKTRACE=1 ./target/debug/dtk rel info ../x4.rel 
REL module ID: 4
REL version: 3
Original section count: 20

Sections:
      Name | Type       | Size       | File Off   | Index     
     .text | code       | 0xDAE20    | 0xEC       | 1         
   .rodata | rodata     | 0x970      | 0xDAF10    | 2         
    .ctors | rodata     | 0x4        | 0xDB880    | 3         
    .dtors | rodata     | 0x4        | 0xDB884    | 4         
     .data | data       | 0x2E57F    | 0xDB8A0    | 5         
      .bss | bss        | 0x1D7E2C   | 0x0        | 6         

Discovered symbols:
   Section | Address    | Size       | Name      
     .text | 0x1CDC     | 0x28C      | _prolog   
    .ctors | 0x0        | ?          | _ctors    
    .dtors | 0x0        | ?          | _dtors    
```

**Comment by encounter** [comment]
Thanks for the investigation & fix!
